language: rust
rust:
  - nightly-2019-09-03
  - nightly
env:
  - NEAR_RELEASE=true
  - NEAR_RELAESE=false

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

branches:
  only:
  - master

script:
  - ./ci-test.sh