[workspace]
members = [
    "near-bindgen",
    "near-bindgen-core",
    "near-bindgen-macros",
]
exclude = [
    "examples/mission-control",
    "examples/dutch-auction",
    "examples/status-message"
]
