[workspace]
members = [
    "near-bindgen",
    "near-bindgen-core",
    "near-bindgen-macros",
]
exclude = [
    "near-bindgen/tests/test-contract",
    "examples/mission-control",
    "examples/dutch-auction"
]
