[package]
name = "mission-control"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
near-bindgen = { path = "../../near-bindgen"}
wee_alloc = { version = "0.4.2", optional = true }
borsh = "0.2.1"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"

[features]
env_test = []

[workspace]
members = []
