[package]
name = "near-bindgen"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
# Provide near_bindgen macros.
near-bindgen-macros = { path = "../near-bindgen-macros"}
serde = { version = "1.0" }
bincode = "1.0"
lazy_static = "1.3.0"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.0"
near-bindgen = { path = "../near-bindgen" }
wasmer-runtime = "0.4.2"
wasm = { git = "https://github.com/nearprotocol/nearcore", branch="prenightshade" }
primitives = { git = "https://github.com/nearprotocol/nearcore", branch="prenightshade" }
rand = "0.7.0"
