[package]
name = "near-bindgen"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
# Provide near_bindgen macros.
near-bindgen-macros = { path = "../near-bindgen-macros"}
serde = { version = "1.0" }
bincode = "1.0"
